### ISSUE TITLE
Drum Fel (NPC in Hammerfall) is missing text

### ISSUE THREAD

**Issue by LuckyLuc96** [gamefreedomgit/Deathwing#35]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I can't find any alternative text that should replace what is here, but right now he simply offers some quests and says, "Need TXT YTDB". It may be better to just remove this text or write a small blurb commenting about the weather or something. 

**How to reproduce:**
1) Go to Hammerfall in Arathi Highlands\
2) Speak to Drum Fel
3) See dialogue says "Need TXT YTDB"

**How it should work:**
4) Dialogue should be something 

**Database links:**
https://www.wowhead.com/classic/npc=2771/drum-fel
![WoWScrnShot_042424_113524](https://github.com/gamefreedomgit/Deathwing/assets/94196417/488d336c-3926-4758-955a-fea9652aa1f8)

**Comment by PanJanuszek** [comment]
fixed 24.04.2024

**Comment by LuckyLuc96** [comment]
Hello. This issue is still present. I visited this fortress today and Poor Drum Fel still has nothing to say. 
![image](https://github.com/gamefreedomgit/Deathwing/assets/94196417/e6d05e23-125a-4873-ba1f-cb0340084152)


> fixed 24.04.2024

**Comment by LuckyLuc96** [comment]
I was perturbed by what the text should be, so I found a video guide for one of his quests on youtube. Which showed his dialogue to be, "We're glad to have your help."

Pause at the 00:01 timemark
https://youtu.be/YdtLIXTvhac?si=SHPPfwYsDVJ2StAf&t=1
